language: java
jdk:
  - oraclejdk8
before_install:
  - eval export AWS_ACCESS_KEY_ID=\$${TRAVIS_BRANCH}_aws_access_key_id
  - eval export AWS_SECRET_ACCESS_KEY=\$${TRAVIS_BRANCH}_aws_secret_access_key
  - eval export AWS_REGION=\$${TRAVIS_BRANCH}_aws_region
  - eval export AWS_DEFAULT_REGION=\$${TRAVIS_BRANCH}_aws_region
  - eval export PACKAGING_S3_BUCKET=\$${TRAVIS_BRANCH}_packaging_s3_bucket
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y jq
  - sudo apt-get install -y python3-pip
  - pip install awscli --upgrade --user
script: mvn verify
